#!/usr/bin/env python3
import json

# Read the gallery data generated by regenerate_gallery.py
with open('gallery_data.json', 'r', encoding='utf-8') as f:
    entries = json.load(f)

# Generate the index.html
gallery_html = f'''<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Week 2 Web Maps Gallery</title>
    <style>
        body {{
            margin: 0;
            padding: 40px 20px;
            background: #fff;
            font-family: 'Courier New', monospace;
        }}
        
        .home-button {{
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 9999;
        }}
        
        .home-button a {{
            background: #000;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            font-family: 'Courier New', monospace;
            font-size: 12px;
        }}
        
        .home-button a:hover {{
            background: #333;
        }}
        
        h1 {{
            text-align: center;
            font-size: 24px;
            margin-bottom: 40px;
            letter-spacing: 2px;
        }}
        
        .gallery {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 20px;
            max-width: 1200px;
            margin: 0 auto;
        }}
        
        .entry {{
            text-align: center;
            cursor: pointer;
        }}
        
        .entry:hover .thumbnail {{
            opacity: 0.8;
        }}
        
        .thumbnail {{
            width: 100%;
            height: 150px;
            background: #f0f0f0;
            border: 2px solid #000;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 14px;
            color: #666;
            margin-bottom: 10px;
            overflow: hidden;
        }}
        
        .thumbnail img {{
            width: 100%;
            height: 100%;
            object-fit: cover;
        }}
        
        .name {{
            font-size: 12px;
            margin-top: 5px;
            color: #000;
        }}
    </style>
</head>
<body>
    <div class="home-button">
        <a href="../index.html">HOME</a>
    </div>
    
    <h1>YOH'S 2026 REITAKU WEB MAPS GALLERY</h1>
    
    <div class="gallery" id="gallery"></div>
    
    <script>
        const entries = {json.dumps(entries, ensure_ascii=False)};
        
        const gallery = document.getElementById('gallery');
        
        entries.forEach(entry => {{
            const div = document.createElement('div');
            div.className = 'entry';
            div.onclick = () => window.location.href = `entry_${{entry.id}}.html`;
            
            const thumb = document.createElement('div');
            thumb.className = 'thumbnail';
            
            // Try screenshot first, then padlet URL as fallback
            let thumbnailUrl = entry.screenshot || entry.padlet || '';
            
            // Check if we have a URL that might be an image
            if (thumbnailUrl && (thumbnailUrl.includes('.png') || thumbnailUrl.includes('.jpg') || thumbnailUrl.includes('.jpeg') || thumbnailUrl.includes('.gif'))) {{
                const img = document.createElement('img');
                img.src = thumbnailUrl;
                img.alt = entry.clean_name;
                img.onerror = function() {{
                    thumb.innerHTML = 'NO IMAGE';
                }};
                thumb.appendChild(img);
            }} else {{
                thumb.textContent = 'NO IMAGE';
            }}
            
            const name = document.createElement('div');
            name.className = 'name';
            name.textContent = entry.clean_name;
            
            div.appendChild(thumb);
            div.appendChild(name);
            gallery.appendChild(div);
        }});
    </script>
</body>
</html>
'''

# Write index.html
with open('index.html', 'w', encoding='utf-8') as f:
    f.write(gallery_html)

print(f"✅ Created index.html with {len(entries)} entries")
